version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_literalura
    environment:
      POSTGRES_DB: literalura
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    restart: always