# Conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Cria as tabelas automaticamente baseado nas suas classes Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console (ótimo para debugar no Codespaces)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true